name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      dynamic_matrix: false
      extra_jobs: |
        - php: 8.0
          phplinting: true
        - php: 8.0
          phpunit: true
        - php: 8.0
          db: mysql57pdo
          phpunit: true
        - php: 8.0
          db: mysql80
          phpunit: true
        - php: 8.1
          phpunit: true
